---
products:
  - name: "Helicopter"
    parts:
        - name: "Motor"
          options:
            - id: "a1"
              name: "M1"
              description: "Milling 15 Drilling 20 Turning 15 Machining 10"
            - id: "a2"
              name: "M2"
              description: "Milling 30 Drilling 30 Turning 20 Machining 15"
            - id: "a3"
              name: "M3"
              description: "Milling 45 Drilling 40 Turning 25 Machining 20"
        - name: "Housing"
          options:
            - id: "a1"
              name: "M1"
              description: "Turning 15 Machining 20 Milling 15 Drilling 20"
            - id: "a2"
              name: "M2"
              description: "Turning 30 Machining 25 Milling 25 Drilling 25"
            - id: "a3"
              name: "M3"
              description: "Turning 45 Machining 30 Milling 35 Drilling 30"
  - name: "Quadcopter"
    parts:
        - name: "Blade"
          options:
            - id: "b1"
              name: "M1"
              description: "Milling 15 Drilling 20 Turning 15 Machining 10"
            - id: "b2"
              name: "M2"
              description: "Milling 30 Drilling 30 Turning 20 Machining 15"
            - id: "b3"
              name: "M3"
              description: "Milling 45 Drilling 40 Turning 25 Machining 20"
        - name: "Frame"
          options:
            - id: "f1"
              name: "M1"
              description: "Turning 15 Machining 20 Milling 15 Drilling 20"
            - id: "f2"
              name: "M2"
              description: "Turning 30 Machining 25 Milling 25 Drilling 25"
            - id: "f3"
              name: "M3"
              description: "Turning 45 Machining 30 Milling 35 Drilling 30"
